'use client';
import { useEffect, useState } from 'react';
import { AdminCard } from '@/components/admin/ui/AdminCard';
import { FieldLabel, TextArea, TextInput } from '@/components/admin/ui/AdminField';
import { AdminTable } from '@/components/admin/ui/AdminTable';

type Post={_id:string;title:string;slug:string;content:string;isPublished:boolean};
export default function AdminBlogPage(){const [items,setItems]=useState<Post[]>([]); const [form,setForm]=useState({id:'',title:'',slug:'',content:'',isPublished:true}); const load=async()=>setItems((await (await fetch('/api/admin/blog')).json()).items||[]); useEffect(()=>{void load();},[]);
const save=async()=>{const method=form.id?'PUT':'POST';const url=form.id?`/api/admin/blog/${form.id}`:'/api/admin/blog';await fetch(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});setForm({id:'',title:'',slug:'',content:'',isPublished:true});void load();};
return <main className="space-y-6"><h1 className="text-2xl font-black">مدیریت بلاگ</h1><AdminCard title="ایجاد/ویرایش مقاله"><div className="grid gap-4 md:grid-cols-2"><div><FieldLabel text="عنوان"/><TextInput value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></div><div><FieldLabel text="اسلاگ"/><TextInput value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></div><div className="md:col-span-2"><FieldLabel text="محتوا"/><TextArea value={form.content} onChange={e=>setForm({...form,content:e.target.value})}/></div><label className="inline-flex items-center gap-2"><input type="checkbox" checked={form.isPublished} onChange={e=>setForm({...form,isPublished:e.target.checked})}/> منتشر شود</label></div><button className="mt-4 h-11 rounded-xl bg-amber-600 px-4 text-white" onClick={save}>{form.id?'ذخیره':'ایجاد'}</button></AdminCard><AdminTable head={<tr className="[&>th]:px-4 [&>th]:py-3 text-right"><th>عنوان</th><th>اسلاگ</th><th>وضعیت</th><th>عملیات</th></tr>}>{items.map(p=><tr key={p._id} className="[&>td]:px-4 [&>td]:py-3"><td>{p.title}</td><td>{p.slug}</td><td>{p.isPublished?'منتشر':'پیش‌نویس'}</td><td><button className="text-amber-700" onClick={()=>setForm({id:p._id,title:p.title,slug:p.slug,content:p.content,isPublished:p.isPublished})}>ویرایش</button> <button className="text-red-600" onClick={async()=>{await fetch(`/api/admin/blog/${p._id}`,{method:'DELETE'});void load();}}>حذف</button></td></tr>)}</AdminTable></main>; }
